import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

import dynamic from "next/dynamic";
const Navigation = dynamic(() => import('@/components/Nav'), {
  ssr: false,
})
import Provider from "@/components/Provider";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KonChat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="en">
        <body className={rubik.className}>
          <div className="bg-background w-screen flex-col flex items-center">
            <Navigation />
            <main>{children}</main>
          </div>
        </body>
      </html>
    </Provider>
  );
}
